module.exports.GAME_STATES = {
  GAME_START: 'GAME_START',
  STOPPED: 'STOPPED',
  FIRST_SCENE: 'FIRST_SCENE_BOAT',
  CHOOSE_BOAT: 'CHOOSE_BOAT',
  CHOOSE_BOAT: 'CHOOSE_BOAT_AGAIN',
  CHOOSE_BOAT_LOOP: 'CHOOSE_BOAT_LOOP',
  CHOOSE_MAN: 'CHOOSE_MAN',

};
