module.exports.GAME_STATES = {
  GAME_START: 'GAME_START',
  STOPPED: 'STOPPED',
  FIRST_SCENE: 'FIRST_SCENE',
  CHOOSE_BOAT: 'CHOOSE_BOAT',
  CHOOSE_BOAT: 'CHOOSE_BOAT_AGAIN',
  CHOOSE_MAN: 'CHOOSE_MAN'
};
